### ISSUE TITLE
Sample is not working

### ISSUE THREAD

**Issue by hjk2022** [energiency/chartjs-plugin-piechart-outlabels#13]
Uncaught TypeError: Cannot read properties of undefined (reading 'helpers')
    at 5f4a0981addb61c99f316391bce57ec089c4d4b9.js:1:350
    at 5f4a0981addb61c99f316391bce57ec089c4d4b9.js:1:179
    at 5f4a0981addb61c99f316391bce57ec089c4d4b9.js:1:202
(index):163 

Uncaught ReferenceError: Samples is not defined
    at (index):163:3
(index):232 

Uncaught ReferenceError: Chart is not defined
    at (index):232:15

**Comment by list5066** [comment]
https://chartjs-plugin-piecharts-outlabels.netlify.app/
